FROM node:14-alpine AS node

# Builder stage

FROM node AS builder

# Use /app as the CWD
WORKDIR /app            

# Copy package.json and package-lock.json to /app
COPY package*.json ./   

# Install all dependencies
RUN npm ci               

# Copy the rest of the code
COPY . .    

# Invoke the build script to transpile code to js
# RUN npm run build       


# Final stage

FROM builder AS final

# Prepare a destination directory for js files
RUN mkdir -p /home/node/app/dist && chown -R node:node /home/node/app

# Use /app as CWD
WORKDIR /home/node/app                      

# Copy package.json and package-lock.json
#COPY package*.json ./

# Switch to user node
USER node             

# Install only production dependencies
#RUN npm ci --only=production             

# Copy transpiled js from builder stage into the final image
COPY --chown=node:node --from=builder /app ./dist
ENV NODE_DEBUG=*
# Open desired port
ENV PORT=3010
EXPOSE 3010

# Use js files to run the application
ENTRYPOINT ["node", "./dist/bin/www"]