apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-k8s-web
  labels:
    app: demo-k8s
spec:
  template:
    metadata:
      labels:
        app: demo-k8s
        tier: web
    spec:
      containers:
      - name: k8s-demo
        image: gcr.io/project/k8s-demo@sha256:a9...d6
        ports:
        - containerPort: 80
      - name: 
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop
  labels:
    app: k8s-workshop
spec:
  type: NodePort
  selector:
    app: frontend
    tier: web
  ports:
  - port: 80
    targetPort: 80
  - port: 3001
    targetPort: 3001
  - port: 3000
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-k8s-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"    

spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: demo-k8s-backend
          servicePort: 3000
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: demo-k8s-backend
          servicePort: 3000