apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-demo-k8s-prod-a
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tom.bulva@gmail.com
    privateKeySecretRef:
      name: demo-k8s-prod-cert
    http01: {}
