apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: demo-k8s-prod-cert
  namespace: default
spec:
  secretName: demo-k8s-prod-cert
  issuerRef:
    name: letsencrypt-demo-k8s-a
    kind: ClusterIssuer
  commonName: k8s-demo.bulva.us
  dnsNames:
  - 'k8s-demo.prod.bulva.us'
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - 'k8s-demo.prod.bulva.us'
